services:
  - type: web
    name: travelaz
    env: docker
    plan: free
    buildCommand: true
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 10000